typography_spectrum: 0.562641175929457
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5262012446764857
  lightness: 0.5289124401751906
  saturation: 0.21440474246628582
  rhythmicContrast: 0.7999699893407524
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.636689007980749
analytics:
  google: null
  facebook: null
  twitter: null
name: glover
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Finally on The Grid
description: And checkin’ it out!
purpose: []
